# Default values for k8s-diagnostics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "thiedebr/k8s-diagnostics"
  pullPolicy: "Always"
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 10000
  seccompProfile:
    type: RuntimeDefault

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

podSecurityGroupIds: []
