name: Helm Lint

on:
  push:
    paths:
      - "/charts/**"
  pull_request:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Lint Helm chart
        run: |
          cd charts/k8s-diagnostics
          helm lint
          helm package .
